const fs = require('fs');
const path = require('path');

const p = path.join('src','pages','focus','InterruptedSessionAlert.tsx');
const s = "import React from 'react';\n\ninterface InterruptedSessionAlertProps {\n  minutes: number;\n  timestamp: string;\n  onConfirm: () => void;\n}\n\nexport default function InterruptedSessionAlert({ minutes, timestamp, onConfirm }: InterruptedSessionAlertProps) {\n  return (\n    <div className=\"fixed inset-0 bg-black/60 backdrop-blur-sm z-50 flex items-center justify-center p-4\">\n      <div className=\"bg-white rounded-3xl shadow-2xl max-w-md w-full p-6 animate-slide-in\">\n        {/* \u6807\u9898\uff08\u5df2\u5220\u9664 \u26a0\ufe0f \uff09 */}\n        <div className=\"text-center mb-4\">\n          <h2 className=\"text-2xl font-bold text-gray-900\">\u4e13\u6ce8\u610f\u5916\u7ed3\u675f</h2>\n        </div>\n\n        {/* \u5185\u5bb9 */}\n        <div className=\"space-y-3 mb-6\">\n          <div className=\"bg-gradient-to-br from-blue-50 to-cyan-50 rounded-xl p-4 border border-blue-100\">\n            <p className=\"text-sm text-gray-600 mb-2\">\u4f60\u4e0a\u6b21\u4e13\u6ce8\u4e86</p>\n            <p className=\"text-3xl font-bold text-blue-600 mb-2\">{minutes} \u5206\u949f</p>\n            <p className=\"text-xs text-gray-500\">\n              {new Date(timestamp).toLocaleString('zh-CN', {\n                year: 'numeric',\n                month: 'short',\n                day: 'numeric',\n                hour: '2-digit',\n                minute: '2-digit',\n              })}\n            </p>\n          </div>\n\n          <div className=\"bg-green-50 rounded-xl p-3 border border-green-100\">\n            <p className=\"text-sm text-gray-700\">\u6211\u4eec\u5df2\u4e3a\u4f60\u8bb0\u5f55\u5230\u4e86\u4e2a\u4eba\u4eea\u8868\u76d8</p>\n          </div>\n\n          <div className=\"bg-amber-50 rounded-xl p-3 border border-amber-100\">\n            <p className=\"text-sm text-amber-700\">\u63d0\u793a\uff1a\u4e13\u6ce8\u8ba1\u65f6\u5668\u5c06\u5728\u51c6\u5907\u72b6\u6001\u4e0b\u7b49\u5f85\u4f60\u7684\u5f52\u6765</p>\n          </div>\n        </div>\n\n        {/* \u6309\u94ae */}\n        <button\n          onClick={onConfirm}\n          className=\"w-full bg-gradient-to-r from-blue-500 to-cyan-500 text-white py-3 px-4 rounded-xl font-semibold hover:from-blue-600 hover:to-cyan-600 transition-all shadow-lg hover:shadow-xl transform hover:scale-[1.02]\"\n        >\n          \u77e5\u9053\u4e86\n        </button>\n      </div>\n    </div>\n  );\n}\n";

fs.mkdirSync(path.dirname(p), { recursive: true });
fs.writeFileSync(p, s, { encoding: 'utf8' });
console.log('[write] ' + p);
